# This is a basic workflow to help you get started with Actions

name: Production Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
    
    - uses: actions/checkout@v1
      
    - name: Use Node.js 12.16.2
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.2
      
    - name: Npm Install
        run:npm install
    - name: Production Build
        run:npm build
    - name: S3 Sync
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "build"
